name: "netbird"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  exit-node:
    image: "11notes/netbird-exit-node:0.65.3"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      NETBIRD_PEER_NAME: "docker"
      NETBIRD_URL: "${NETBIRD_URL}"
      NETBIRD_SETUP_KEY: "${NETBIRD_SETUP_KEY}"
    volumes:
      - "exit-node.etc:/netbird/etc"
    tmpfs:
      - "/run:uid=1000,gid=1000"
    networks:
      frontend:
    restart: "always"

volumes:
  exit-node.etc:

networks:
  frontend: